### PR TITLE
Create bst

### PR DESCRIPTION
**Pull request by Gankra**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @apasel422

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
Whoops, accidentally just pushed cons-list.json (trying the pure-github UI). Ah well.

**Comment by FlashCat** [comment]
:umbrella: The latest upstream changes (presumably 8bfa50b) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by huonw** [comment]
Oh, did this manually, whoops. I believe cons-list and bst are not configured for both highfive and homu.

**Comment by Gankra** [comment]
*are now?

**Comment by huonw** [comment]
Yeah, whoops.

**Pull request closed without merging**
